#!/bin/bash
#Created by Marie McAdams and Adam Kuphaldt on 6/10/2015
# Purpose: Checks the Puerto Rico lower 15 IP addresses to see if they are still in use

#saves the IP address in one file, and the result (pass or fail) in the other file, so they match up and can both be integrated into the spreadsheet
echo "Addresses Status File:" > addressesStatusTest
echo "Addresses File:" > addressesTest
#loops to check all of the ip addresses from Puerto Rico (from 15.29.16.0 to 15.29.23.255)
for (( i = 16 ; i <= 23; i++ ))
do
	for (( j = 0 ; j <= 255; j++ ))
	do
		address=15.29.$i.$j
		ping -c 1 15.29.$i.$j
		if [ $? -gt 0 ]
		#failed ping
		then
			echo "Didn't connect. Invalid IP address, IP address not in use, or internet proxies preventing connection."
			echo $address >> addressesTest
			echo fail >> addressesStatusTest
		#passed ping
		else
			echo "Successfully pinged!"
			echo $address >> addressesTest
			echo success >> addressesStatusTest
		fi
done
done
